name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
        
      - name: Build with maven
        run: ./mvnw -B package

  integration-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
        
      - name: Build with maven
        run: ./mvnw -B verify

  build-image:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - run: echo "build image"

  deploy:
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - run: echo "deploy"
